// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1p18j-22Vb8F2-mDnNbezOUhMEIvJSm0',
    appId: '1:470967179718:web:5bec048c1ac87de8ce7ac7',
    messagingSenderId: '470967179718',
    projectId: 'aqarcom-4cc7a',
    authDomain: 'aqarcom-4cc7a.firebaseapp.com',
    storageBucket: 'aqarcom-4cc7a.appspot.com',
    measurementId: 'G-QLCVVLQ90M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJw5vwtKMKTyX0Vy9TSBa5o8Hys9iLdA',
    appId: '1:470967179718:android:496f5fb19bccb9aece7ac7',
    messagingSenderId: '470967179718',
    projectId: 'aqarcom-4cc7a',
    storageBucket: 'aqarcom-4cc7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQa_EGBhGRUVjV_8KnJGNglttsDeEr1n4',
    appId: '1:470967179718:ios:45d3b922f5e5c820ce7ac7',
    messagingSenderId: '470967179718',
    projectId: 'aqarcom-4cc7a',
    storageBucket: 'aqarcom-4cc7a.appspot.com',
    iosBundleId: 'com.example.aqarcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQa_EGBhGRUVjV_8KnJGNglttsDeEr1n4',
    appId: '1:470967179718:ios:45d3b922f5e5c820ce7ac7',
    messagingSenderId: '470967179718',
    projectId: 'aqarcom-4cc7a',
    storageBucket: 'aqarcom-4cc7a.appspot.com',
    iosBundleId: 'com.example.aqarcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1p18j-22Vb8F2-mDnNbezOUhMEIvJSm0',
    appId: '1:470967179718:web:70568d666b1c80bace7ac7',
    messagingSenderId: '470967179718',
    projectId: 'aqarcom-4cc7a',
    authDomain: 'aqarcom-4cc7a.firebaseapp.com',
    storageBucket: 'aqarcom-4cc7a.appspot.com',
    measurementId: 'G-MWNXJY86LZ',
  );
}
